### ISSUE TITLE
Logger Multithreading Bug

### ISSUE THREAD

**Issue by harrydehix** [STAMACODING/RSA-App#35]
**Describe the bug**
Wenn man von mehreren Threads aus den Logger benutzt, kommt es manchmal zu seiner _NoSuchFileException_, manchmal auch zu seiner _FileNotFoundException_. Dies liegt wahrscheinlich an mehreren Zugriffen im gleichen Augenblick auf diesselbe Datei.

**To Reproduce**
Führe folgendes Programm aus - stellvertretend für den _MessageService_ mit all seinen vielen Threads.
```java
public static void main(String[] args){
	new Thread(new Runnable() {
		
		@Override
		public void run() {
			for(int i=0; i<=3000000; i++) {
				Logger.debug("hhd", "test");
				try {
					Thread.sleep(100);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		}
	}).start();
	new Thread(new Runnable() {
		
		@Override
		public void run() {
			for(int i=0; i<=3000000; i++) {
				Logger.debug("hhd", "test");
				try {
					Thread.sleep(100);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		}
	}).start();
	new Thread(new Runnable() {
		
		@Override
		public void run() {
			for(int i=0; i<=3000000; i++) {
				Logger.debug("hhd", "test");
				try {
					Thread.sleep(100);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		}
	}).start();
	new Thread(new Runnable() {
		
		@Override
		public void run() {
			for(int i=0; i<=3000000; i++) {
				Logger.debug("hhd", "test");
				try {
					Thread.sleep(100);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		}
	}).start();
}
```

**Expected behavior**
Loggen ohne Fehler.

**Die aufkommenden Exceptions**
A) FileNotFoundException
```java
java.io.FileNotFoundException: logs\Main.log (Zugriff verweigert)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:158)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:82)
	at com.stamacoding.rsaApp.log.filesystem.Filesystem.appendToFile(Filesystem.java:78)
	at com.stamacoding.rsaApp.log.filesystem.Filesystem.appendToFile(Filesystem.java:53)
	at com.stamacoding.rsaApp.log.filesystem.Filesystem.deleteLines(Filesystem.java:117)
	at com.stamacoding.rsaApp.log.filesystem.Filesystem.appendToFile(Filesystem.java:71)
	at com.stamacoding.rsaApp.log.logger.Logger.printToFile(Logger.java:144)
	at com.stamacoding.rsaApp.log.logger.Logger.log(Logger.java:113)
	at com.stamacoding.rsaApp.log.logger.Logger.debug(Logger.java:74)
	at server.message.Message$2.run(Message.java:240)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
B) NoSuchFileException
```java
java.nio.file.NoSuchFileException: logs\Main.log
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:155)
	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2838)
	at com.stamacoding.rsaApp.log.filesystem.Filesystem.readLines(Filesystem.java:143)
	at com.stamacoding.rsaApp.log.filesystem.Filesystem.deleteLines(Filesystem.java:102)
	at com.stamacoding.rsaApp.log.filesystem.Filesystem.appendToFile(Filesystem.java:71)
	at com.stamacoding.rsaApp.log.logger.Logger.printToFile(Logger.java:144)
	at com.stamacoding.rsaApp.log.logger.Logger.log(Logger.java:113)
	at com.stamacoding.rsaApp.log.logger.Logger.debug(Logger.java:74)
	at server.message.Message$1.run(Message.java:226)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by MrTK-Dev** [comment]
# Main Idea

Create different files for each thread to avoid the usage of a queue.

- [ ] Retrieve data about the current thread
- [ ] Create files depending on the current thread
- [ ] Add support in the FileSystem
- [ ] Test it

## Alternative

Use a queue to avoid overlaping of multiple threads on the same file.
